# Generated by Django 4.0.3 on 2022-03-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together={('sent_id', 'text')},
        ),
    ]
