# Generated by Django 4.0.3 on 2022-03-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_alter_sentence_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='notes',
            field=models.TextField(),
        ),
    ]
