# Generated by Django 4.0.3 on 2022-03-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_alter_annotation_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='cats',
        ),
        migrations.CreateModel(
            name='Word_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_f', models.CharField(max_length=10)),
                ('form_f', models.CharField(max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('upos', models.CharField(max_length=100)),
                ('xpos', models.CharField(max_length=100)),
                ('feats', models.CharField(max_length=500)),
                ('head', models.IntegerField()),
                ('deprel', models.CharField(max_length=100)),
                ('deps', models.CharField(max_length=100)),
                ('misc', models.CharField(max_length=200)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.annotation')),
            ],
        ),
    ]
