# Generated by Django 4.0.3 on 2022-03-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_remove_annotation_cats_word_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_line',
            name='head',
            field=models.CharField(max_length=100),
        ),
    ]
