# Generated by Django 4.0.3 on 2022-03-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_extenduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word_line',
            old_name='form_f',
            new_name='form',
        ),
    ]
