# Generated by Django 4.0.3 on 2022-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0012_rename_form_f_word_line_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='status',
            field=models.CharField(default='not', max_length=20),
            preserve_default=False,
        ),
    ]
