# Generated by Django 4.0.3 on 2022-08-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_treebankfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='treebankfile',
            name='name',
            field=models.CharField(default=555, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
