# Generated by Django 4.0.3 on 2022-08-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0016_treebankfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treebankfile',
            name='name',
        ),
    ]
